inherits = "base16_default_light"

"ui.background" = { bg = "white"}
"ui.gutter" = { bg = "default", fg = "base04"}
"ui.statusline" = { bg = "default" }
"ui.menu" = { bg = "default" }
"ui.linenr" = { fg = "base04", bg = "defualt" }
"ui.linenr.selected" = { bg = "default", fg = "black" }
"ui.cursorline.primary" = { bg = "highlight"}
"ui.cursor" = { fg = "totalblack", modifiers = ["reversed", "rapid_blink"] }
"ui.cursor.primary" = { fg = "totalblack", modifiers = ["reversed", "rapid_blink"] }

"operator" = "gray"
"punctuation" = "blue"
"variable" = "magenta"
"constant.numeric" = "red"
"constant" = "red"
"attribute" = "magenta"
"type" = "green"
"string"  = "red"
"variable.other.member" = "magenta"
"constant.character.escape" = "magenta"
"function" = "magenta"
"constructor" = "blue"
"special" = "blue"
"keyword" = "blue"
"label" = "blue"
"namespace" = "green"

[palette]
highlight = "#ffffe6"
base00 = "#f8f8f8" # Default Background
base01 = "#e8e8e8" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#b3d7ff" # Selection Background
base03 = "#b8b8b8" # Comments, Invisibles, Line Highlighting
base04 = "#999999" # Dark Foreground (Used for status bars)
base05 = "#383838" # Default Foreground, Caret, Delimiters, Operators
base06 = "#282828" # Light Foreground (Not often used)
base07 = "#181818" # Light Background (Not often used)
base08 = "#ab4642" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#dc9656" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f7ca88" # Classes, Markup Bold, Search Text Background
base0B = "#a1b56c" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#86c1b9" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#7cafc2" # Functions, Methods, Attribute IDs, Headings
base0E = "#ba8baf" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a16946" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
totalblack = "#000000"
